### ISSUE TITLE
Unresolved Issues Checklist

### ISSUE THREAD

**Issue by mayork** [hoburg/d8#28]
**Both**
- [x] max wing alpha is in cruise not climb...I think this is messing up the wing sizing

**737-800**
- [x] solver behavior drastically changes when slack variables are raised to a power other than 20 (solved by https://github.com/hoburg/d8/commit/8033050346fcb90cec03c0fa382adf631d0a38d0)
- [x] `'M_{takeoff}, \theta_{db}, w_{db}`  relaxed after final GP solve in 737-800 case
UPDATE: after excluding these variables from the relaxation the problem will not solve, we simply      bounce back and forth between two points as indicated by the print out below (solved by https://github.com/hoburg/d8/commit/8033050346fcb90cec03c0fa382adf631d0a38d0)
```
In [22]: m_relax.program.gps[-1].solver_out['objective']
Out[22]: 2.542345540169875e+82

In [23]: m_relax.program.gps[-2].solver_out['objective']
Out[23]: 2.7501349881586006e+82

In [24]: m_relax.program.gps[-3].solver_out['objective']
Out[24]: 2.5423455316718514e+82

In [25]: m_relax.program.gps[-4].solver_out['objective']
Out[25]: 2.7501349776378666e+82
```
- [x] Fuselage and tail drag coefficients are too large [confident in what we have, disregarding]
- [x] VT volume coefficient must be specified, doesn't solve with value under 0.09likely due to CG model
- [x] HT TCS warnings 
- [x] Moment of inertia TCS warnings (one error is >6,000%)
- [x] SM margin is too low, model won't solve with SM_min set to the TASOPT SM of 0.38
- [x] TASOPT e is 0.917 ours is 0.9559, I'm not sure why [seems to be non-issue, checking off]

**D8.2**
- [x] HT weight >600% low

**Comment by mayork** [comment]
@1ozturkbe lets keep all issues in the checklist and check them off as we go

**Comment by mayork** [comment]
@1ozturkbe what is up with this TCS warning from the 737, the actual error is massive

```
Warning: Constraint [I_{z}_Mission, Aircraft, VerticalTail, VerticalTailNoStruct [kg*m**2]... >= I_{z_{fuse}}_Mission, Aircraft + I_{z_{tail}}_Mission, Aircraft + I_{z_{wing}}_Mission, Aircraft [kg...] is not tight because the left hand side evaluated to 11573434586.4 kilogram * meter ** 2 but the right hand side evaluated to 171359706.721 kilogram * meter ** 2 (Allowable error: 0.1%, Actual error: 6.7e+03%)
```

**Comment by 1ozturkbe** [comment]
I know what is going on I think... once I confirm my suspicions I will update this.

**Comment by 1ozturkbe** [comment]
That was because the yaw rate constraint was not active, and there was no downward pressure on any of the moment of inertia variables... Annoying, but not problematic. I am in the process of fixing the CG calculations.

**Comment by mayork** [comment]
@1ozturkbe i'm thinking this constraint might not be correct (or even necessary) in the HT and VT model (it is never tight)

```python
               TCS([dxlead + self.HT['y_{\\bar{c}_{ht}}']*self.HT['\\tan(\\Lambda_{ht})'] + 0.25*self.HT['\\bar{c}_{ht}'] >= self.HT['l_{ht}']],
                    reltol=1e-2), # [SP]     
```
I don't see how this sets anything that isn't set elsewhere and running with it commented out seems to yield the same answer.

Okay deleting?

**Comment by 1ozturkbe** [comment]
I frankly have no idea what that constraint even is... If it is not useful delete it!

**Comment by mayork** [comment]
also - should the CG constraints be tight? If not, can we remove TCS from the ones we don't expect to be tight?

**Comment by 1ozturkbe** [comment]
I am doing my best to put in better CG constraints, but every time I make a change I make the models go UNKNOWN or dual infeasible, taking a lot of time to debug. The CG constraints should be tight in the end; or else, I will replace the constraint with a SigEq.

**Comment by mayork** [comment]
sounds good....might have to investigate using a SigEq because i'm seeing that none of them are tight and some of the errors are pretty large

**Comment by 1ozturkbe** [comment]
The 737 model is extremely unstable, and I am not sure why, and I don't want to push my changes until I have a better idea why. (And I have moved all of the weight variables to the Aircraft() model from Mission())

**Comment by mayork** [comment]
unstable like sometimes it solves and sometimes it doesn't?

**Comment by 1ozturkbe** [comment]
No, meaning it should be more robust to changes in substitutions. It should not be breaking down when I relax A_{vt} or change the yaw rate constraint.

**Comment by mayork** [comment]
yeah i agree...i'm seeing similar behavior. I thought one approach might be to ignore that until we fix the bugs we know of...small chance we get lucky and that solves the problem

**Comment by mayork** [comment]
so do we have any kind of fuselage lift model?

**Comment by 1ozturkbe** [comment]
We need one... There some things about fuselage lift fraction in the TASOPT papers (something about a 21% CL reduction at wing root, but added lift from fuselage etc) that we can dig up. It will likely be some simpmle function of fuselage dimensions and wing cruise CL.

**Comment by mayork** [comment]
yeah seems important because even for the 737 11% of the lift is from the fuse. you want to do this or you want me to?

**Comment by 1ozturkbe** [comment]
You start working on it. I am trying to get the CG stuff working... And guess what? As I was writing this message, I got the first working solve of 737! Hell yes.

**Comment by 1ozturkbe** [comment]
And all of the outputs make sense. The problem was with the CG constraint. Refining now.

**Comment by mayork** [comment]
push it up i'd like to take a look

**Comment by 1ozturkbe** [comment]
Sounds good. Give me a few mins to clean up. I did a temporary fix by only sizing CG by the dry weight for 737. But I am going to start doing it using a percent fuel remaining variable.

**Comment by mayork** [comment]
@1ozturkbe i'm still showing the fuselage drag is 96% too large, any idea what's going on there?

**Comment by 1ozturkbe** [comment]
I have no idea... I very blindly had put in Philippe's fuselage model based on the 737 as a placeholder. Needs refinement. I'll add to the list of things at the top.

**Comment by 1ozturkbe** [comment]
Btw, now the b737 solves without the lower bounding on V_{vt}. Checking it off.

**Comment by mayork** [comment]
sounds good. I'm questioning the reynolds number drag fits, swapped the wing out with a different fit I had the percent error is now less than one

**Comment by mayork** [comment]
@1ozturkbe the Reynolds number appears to be about 6% low at altitude due to our atmosphere model...is this an issue for the fuselage drag? Doesn't seem to be the problem with the tail drag.

**Comment by 1ozturkbe** [comment]
Well, the fuselage viscous drag is a f'n of Re**0.8, so it will have some effect on that (~5%), but likely effect on total fuselage drag is low (1~2%) since the form drag is currently independent of Re, and viscous drag only makes up around 25% of the total fuselage drag. Is it because of the atmospheric fit that we are off? In either case, I think that we need to have a better approximation for fuselage drag (or use a fudge factor to scale to get it closer to TASOPT).

**Comment by mayork** [comment]
yep it's because TASOPT is using a standard atmosphere model but we neglect the troposphere/tropopause transition...but it doesn't seem to be a driving factor in any of the drag errors

**Comment by mayork** [comment]
by upping the minimum static margin to align with the min in the tastopt output i was able to bring the HT weight in to only 33% low

**Comment by mayork** [comment]
Here's something  I don't understand...increasing the exponent penalty on relaxation does not change the amount of relaxation...are we not feasible without relaxation?

**Comment by 1ozturkbe** [comment]
Possibly... what does it relax? When I was running it it was just wingspan, which would suggest our wing weight or max lift model is a little off.

**Comment by 1ozturkbe** [comment]
What do we use for the T/O CL?

**Comment by mayork** [comment]
well if you exclude wing span it relaxes min mach and 3 engine parameters

**Comment by mayork** [comment]
seems like there's no way to relax nothing

**Comment by 1ozturkbe** [comment]
I think we are using 2.15 for TO CL, no? I'm pretty certain the CL can be higher than that for the 73, because it has slats?

**Comment by 1ozturkbe** [comment]
It's 2.15 for the D8 because it doesn't have slats (also, have we made sure that f_{slat} is 0.0000001 for D8?

**Comment by mayork** [comment]
yeah f_{slat} is right in the D8....in the TASOPT output the TO CL is  1.2622 for the 737...

**Comment by mayork** [comment]
i think we should try using the relaxed solution as a guess in a non-relaxed solve...unfortunately
this doesn't work
```python
        sol = m_relax.localsolve( verbosity = 4, iteration_limit=200)

        sol2 = m.localsolve( verbosity = 4, iteration_limit=200, x0=sol)
```

**Comment by bqpd** [comment]
My guess is that the relaxation is showing a fundamental primal
infeasibility...

**Comment by 1ozturkbe** [comment]
I think this has to do with our wing area being massive (I think about 40% more than the 737-8 if I remember correctly). A T/O CL of 1.26 seems low to me, and I think might actually be increasing the wing size and weight significantly.

**Comment by mayork** [comment]
out max CL is currently set to the D8 value, not the 1.26

**Comment by 1ozturkbe** [comment]
So our wing area is set at landing then? I'm just trying to figure out why the wing is so huge.

**Comment by mayork** [comment]
the wing is large because the first climb segment CL is 0.75 low. I'm not sure why though, looking into this more.

**Comment by 1ozturkbe** [comment]
I don't think that's an issue: you are travelling relatively fast while climbing, whereas during t/o and landing you are using a v that is some factor of stall speed. I suspect that the fully-fuelled (?) landing is pushing the wing area up significantly.

**Comment by 1ozturkbe** [comment]
Also, if you have resolved the SM issue, you should definitely check it off.

**Comment by mayork** [comment]
where are we considering landing? i'm not aware of landing in any of our models

and i'm not convinced it's actually resolved the HT area and weight still don't alight fully

**Comment by 1ozturkbe** [comment]
We don't consider landing? Then how come there is a landing speed? We definitely should be considering it; I am almost certain that is what sizes the wing for the 73. 
Also, can you make that second sentence grammatical? I don't understand what you mean :P

**Comment by mayork** [comment]
where do we have a  landing speed?

**Comment by mayork** [comment]
can the 73 even take a MTOW landing? a lot of jets can't, you just fuel dump to meet the landing weight reqt. the only jet i know of that can lad at MTOW is the 757

**Comment by 1ozturkbe** [comment]
73 and the 75 are the only Boeing A/C that can. and V_{land} is specified somewhere; just look at sol('V_{land}')

**Comment by mayork** [comment]
ah gotcha didn't realize the 73 had that capability.

and the Vland is only for sizing the VT with the flare yaw rate acceleration constraint

**Comment by 1ozturkbe** [comment]
I will add check the wing sizing out, after I get the turbofan import working.

**Comment by mayork** [comment]
@1ozturkbe are we taking into account how sweeping the wing decreases the effective mach number by cos(sweep)? As far as I know we are not, this could explain our overshoot on total drag

**Comment by 1ozturkbe** [comment]
Well, I have never taken a look at the wing drag model in great detail, but it doesn't seem to have any accounting for this... seems like a pretty severe weakness. There should definitely be a cos^2(sweep) term in the wing drag with Mach number. Do you have any idea how to attack this?

**Comment by mayork** [comment]
yeah i can fix it rn

**Comment by mayork** [comment]
well fixing that removes the relaxation on the mach number. we're down to just the relaxation on the wing span.

**Comment by mayork** [comment]
hmm. well enforcing our oswald eff factor to be the same as TASOPTs does not solve the wing issues

**Comment by mayork** [comment]
@1ozturkbe i think i'd be comfortable closing out the 737 case, we're a little high on fuel burn but it's cause we're high on drag. I think we have a good reliable model.

**Comment by mayork** [comment]
regarding D8.2 HT weight i'm wondering if we were wrong about TASOPT taking into account the structural benefits of the pi tail....should we ask mark?

**Comment by 1ozturkbe** [comment]
I am confident about the 73 as well. For the HT I agree we should ask Mark... I'm also a little skeptical about our model as well. Perhaps we should reconsider it? The way it's done now is through the moment balance at the VT joint at max load, and the maximum bending load in the middle of the HT. But we don't really consider whether we need extra shear reinforcement at the joints, and I'm not sure if need to to consider other load cases. I'm just terrible at structures... :P

**Comment by mayork** [comment]
lol you're better than me at structures. we could try reverting to the original model and seeing how that works...we've made a lot of improvements since we tried it

**Comment by 1ozturkbe** [comment]
As of 25d4d40b, the HT weight is within 10%. I think we can check this off, it had to do with a bad approx for root bending moment for the HT.

**Comment by 1ozturkbe** [comment]
The only issue remaining is the oswald efficiency factor e. Although we are high on this, as of 25d4d40b, our wing drag is 122% high? Or do we have some wrong calculation?

**Comment by mayork** [comment]
nothing outstanding, closing for now
